### ISSUE TITLE
copy_latest() error due to latest date calculation

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/parser-rosstat-kep#110]
```
>>> import manage
>>> manage.copy_latest()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\PogrebnyakEV\Desktop\mini-kep\kep\src\manage.py", line 36, in copy_latest
    shutil.copyfile(src, dst)
  File "D:\Continuum\Anaconda3\lib\shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\PogrebnyakEV\\Desktop\\mini-kep\\kep\\data\\processed\\2017\\10\\dfa.csv'
```

**Comment by hayksar** [comment]
supported_dates() function in config.py returns the current date, while the latest data is for 10.2017.

    def test_supported_dates_ends_with_latest_date():
        base_dir = find_repo_root()
        latest_year, latest_month = get_latest_date(base_dir / 'data' / 'interim')
>       assert supported_dates()[-1] == (latest_year, latest_month)
E       assert (2017, 11) == (2017, 10)
E         At index 1 diff: 11 != 10

**Comment by epogrebnyak** [comment]
Depreciated `latest` functionality
