### ISSUE TITLE
shorter decimal representation in CSV file

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/parser-rosstat-kep#157]
On output we have values like 9932.600000000002, while the actual value is 9932.6 (see https://github.com/mini-kep/parser-rosstat-kep/blob/dev/data/processed/2017/12/dfq.csv)

Can we ensure we write 9932.6 to csv files? Maybe shoud use [decimal](https://docs.python.org/2/library/decimal.html) representation.

**Comment by Inkognita** [comment]
Actually the values are becoming longer in [create_dataframe()](https://github.com/mini-kep/parser-rosstat-kep/blob/57d50016e949f25e9754d7364a8843205709642e/src/kep/csv2df/dataframe_maker.py#L22) and when taking diff() of df in [deacc_main()](https://github.com/mini-kep/parser-rosstat-kep/blob/57d50016e949f25e9754d7364a8843205709642e/src/kep/csv2df/dataframe_maker.py#L73)

**Comment by epogrebnyak** [comment]
Great, but what should be done next? Anyhting in line of: https://stackoverflow.com/questions/19912611/pandas-script-modifying-numbers-to-long-float-numbers-when-it-shouldnt-even-be

>Try changing your to_csv lines to include the argument float_format='%.4f' which will round things to 2 decimal places.
