### ISSUE TITLE
adapt code to create html with headers and charts

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/parser-rosstat-kep#172]
Goal: gererate a pdf file similar to picture below: 

![image](https://user-images.githubusercontent.com/9265326/41750259-a3ffc000-75c3-11e8-969f-87fd1cbb6cdc.png)

Pseudocode:
 - [x] read dataframes 
 - [x] read layout from yaml file 
 - [ ] generate plots [+] and save as .png files, 
 - [ ] populate `table_doc` string with jinja
 - [ ] insert `table_doc` to `html_doc`
 - [ ] save `html_doc` as local file
 - [ ] generate pdf file
 - [ ] optional: make unittest test for comparing the refernce file and result of operation 

Must create new branch `dev-jinja` for this.

**Comment by epogrebnyak** [comment]
Please use this link: https://github.com/mini-kep/parser-rosstat-kep/blob/dev/notebook/current/curwork.py

**Comment by epogrebnyak** [comment]
Это должно быть частью темплейта: 

trow.append("""<img class="rowimage" src="./%s_%s.png" ></img>"""

в него также желательно передавать что-то более читаемое чем item[0]

**Comment by epogrebnyak** [comment]
в идеале также заголовок обернуть в свой класс <div> и уменьшить количество пустого пространства
также нужно какое-то решение  для размещения разрыва страниц, если знаете.

**Comment by annndrey** [comment]
Уменьшены отступы страниц, добавлен принудительный разрыв страницы перед 4 заголовком, чтобы он оставался на одной странице с графиками

**Comment by epogrebnyak** [comment]
@annndrey, см комментарии в https://github.com/mini-kep/parser-rosstat-kep/commit/87a0a06addfdae9f9b2e0881ca9d8196bfd188cf#commitcomment-29474023

**Comment by epogrebnyak** [comment]
Текущие проблемы:
- в html не читаются заголовки блоков из-за проблемы с кодировкой
- желательна Windows-совместимая библиотека для создания pdf (`pdfkit`?), `weasyprint` не подходит
