### ISSUE TITLE
frontend: put code for graphs in one place

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/parser-rosstat-kep#78]
Есть три варианта отрисовки данных :
1. <https://github.com/epogrebnyak/mini-kep/blob/master/src/frontpage/VALUES.md> - сплайны, код где-то в папке frontpage 
![image1](https://user-images.githubusercontent.com/11600722/29885625-2ec8903c-8dc0-11e7-85ce-d51e091e615f.png)

2. <https://github.com/epogrebnyak/data-rosstat-kep> и код [тут](https://github.com/epogrebnyak/data-rosstat-kep/blob/master/kep/getter/plots.py)
![image2](https://user-images.githubusercontent.com/11600722/29885642-3907aea2-8dc0-11e7-8ea1-5d60b1ad118c.png)

3. https://github.com/epogrebnyak/data-lab (группы показателей)
![image3](https://user-images.githubusercontent.com/11600722/29885655-42981f88-8dc0-11e7-9db4-bbcb27bab48f.png)

Мне не нравится, что это три разные отрисовки, код в разных местах. Первая задача собрать код этих рисунков в одном месте.

**Comment by mousehead** [comment]
https://github.com/epogrebnyak/Business-Conditions-Digest-2017

https://github.com/epogrebnyak/plotting/tree/master/pdf-plotting-backend

**Comment by epogrebnyak** [comment]
Visualisations moved to https://github.com/mini-kep/user-charts/blob/master/viz.py
